# Generated by Django 3.2.6 on 2021-08-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_layer', '0002_auto_20210818_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider_logo_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
