# Generated by Django 3.2.6 on 2021-08-18 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('true_layer', '0003_alter_account_provider_logo_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('description', models.TextField(blank=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(max_length=50)),
                ('transaction_category', models.CharField(max_length=50)),
                ('transaction_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_id', models.CharField(max_length=50)),
                ('provider_transaction_id', models.CharField(max_length=50)),
                ('normalised_provider_transaction_id', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='true_layer.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
