# Generated by Django 3.2.6 on 2021-08-18 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('true_layer', '0005_alter_accounttransaction_transaction_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('account_id', models.CharField(max_length=50)),
                ('card_network', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('partial_card_number', models.CharField(max_length=50)),
                ('name_on_card', models.CharField(max_length=50)),
                ('provider_display_name', models.CharField(max_length=50)),
                ('provider_id', models.CharField(max_length=50)),
                ('provider_logo_uri', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
